import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import type { Language } from "../types/api";

type Dict = Record<string, string>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const dictionary: Record<Language, Dict> = {
  en: {
    appTitle: "Talents We Trust | Job Seeker",
    pulse: "The Pulse",
    opportunities: "Opportunity Map",
    cvLab: "CV Lab",
    aiConsultant: "AI Consultant",
    market: "Market",
    consultants: "Consultants",
    applications: "Applications",
    profile: "Profile",
    settings: "Settings",
    searchPlaceholder: "Search jobs, companies, skills...",
    premiumUpgrade: "Premium Upgrade",
    login: "Login",
    register: "Create account",
    forgotPassword: "Forgot password",
    resetPassword: "Reset password",
    email: "Email",
    password: "Password",
    fullName: "Full name",
    phone: "Phone",
    submit: "Submit",
    logout: "Logout",
    atsHealth: "ATS Health",
    applicationFunnel: "Application Funnel",
    skillRadar: "Skill Radar",
    quickApply: "Quick Apply + Smart Pitch",
    aiStudio: "AI Studio",
    mockInterview: "Mock Interview Mode",
    welcomeBack: "Welcome Back",
    accessWorkspace: "Access your seeker workspace.",
    createJobSeekerAccount: "Create Job Seeker Account",
    registrationWorkflow: "From registration to applications in one workflow.",
    loginFailed: "Login failed",
    registrationFailed: "Registration failed",
    authFailed: "Failed",
    resetLinkSent: "If the email exists, a reset link has been sent.",
    passwordResetDone: "Password reset completed.",
    createAccount: "Create account",
    alreadyHaveAccount: "Already have an account?",
    forgotPasswordQ: "Forgot password?",
    sendResetLink: "Send reset link",
    haveTokenResetHere: "Have token already? Reset here",
    resetToken: "Reset Token",
    newPassword: "New Password",
    resetPasswordBtn: "Reset password",
    backToLogin: "Back to login",
    authTagline: "AI-Powered Career Intelligence",
    authHeadline: "Professional Job Seeker Command Center",
    authDescription: "Registration, CV Lab, AI consultant, market discovery, and premium insights.",
    goodMorning: "Good morning",
    seeker: "Seeker",
    profileMatchPrefix: "Your profile is a",
    profileMatchMiddle: "Match for",
    profileMatchSuffix: "new roles.",
    currentCvStrength: "Current CV strength",
    applied: "Applied",
    interview: "Interview",
    offer: "Offer",
    marketLabel: "Market",
    opportunitiesTitle: "Opportunity Map",
    opportunitiesSubtitle: "Infinite smart cards with Match Intensity and Quick Apply.",
    uploadCvFirst: "Upload CV first in CV Lab",
    quickApplySuccess: "Quick apply submitted with Smart Pitch.",
    quickApplyFailed: "Quick apply failed",
    match: "Match",
    company: "Company",
    remote: "Remote",
    save: "Save",
    loadMore: "Load More",
    cvPreview: "CV Preview",
    uploadCv: "Upload CV",
    deleteCv: "Delete CV",
    analyze: "Analyze",
    aiRecommendations: "AI Recommendations",
    pasteBulletsPlaceholder: "Paste bullet points for live phrasing feedback...",
    weakPhrasing: "Weak Phrasing",
    noWeakPhrases: "No weak phrases detected",
    strongImpact: "Strong Impact",
    addImpactVerbs: "Add stronger impact verbs",
    templateSwitcherNote: "Template switcher: use AI Consultant export for PDF/DOCX generation.",
    selectCvFirst: "Select CV first",
    startSession: "Start Session",
    selectSession: "Select session",
    askPlaceholder: "Ask for interview prep, career strategy, CV improvements...",
    send: "Send",
    marketTitle: "The Market",
    marketSubtitle: "Approved-only company discovery with culture signal preview.",
    noDescriptionYet: "No description yet",
    cultureScore: "Culture Score",
    consultantMarketplace: "Consultant Marketplace",
    generalConsulting: "General consulting",
    auditBookingTitle: "15-Min Audit Booking",
    selectConsultant: "Select consultant",
    auditGoalsPlaceholder: "Write your goals for this audit...",
    bookSlot: "Book 15-min Slot",
    bookedSuccess: "15-minute audit booked successfully.",
    bookingFailed: "Booking failed",
    consultantsLoadFailed: "Failed to load consultants.",
    selectConsultantAndTime: "Select consultant and start time",
    applicationsTitle: "Applications",
    applicationFallback: "Application",
    savedJobs: "Saved Jobs",
    remove: "Remove",
    notifications: "Notifications",
    markAsRead: "Mark as Read",
    loading: "Loading",
    uploading: "Uploading CV...",
    cvUploadSuccess: "CV uploaded successfully.",
    cvUploadFailed: "Failed to upload CV.",
    settingsSubtitle: "Manage language, theme, and account preferences.",
    language: "Language",
    theme: "Theme",
    themeDark: "Dark",
    themeLight: "Light",
    themePremium: "Premium",
    accountActions: "Account Actions",
    showAllNotifications: "Show all notifications",
    noNotificationsYet: "No notifications yet.",
    unread: "Unread",
    profileInfo: "Profile Information",
    cvAiInsights: "CV AI Insights",
    noAiInsightsYet: "No AI insights yet. Analyze your CV in CV Lab.",
    strengths: "Strengths",
    weaknesses: "Weaknesses",
    recommendations: "Recommendations",
    noData: "No data available.",
  },
  ar: {
    appTitle: "Talents We Trust | الباحث عن عمل",
    pulse: "النبض",
    opportunities: "خريطة الفرص",
    cvLab: "مختبر السيرة",
    aiConsultant: "المستشار الذكي",
    market: "السوق",
    consultants: "سوق المستشارين",
    applications: "الطلبات",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    searchPlaceholder: "ابحث عن وظيفة أو شركة أو مهارة...",
    premiumUpgrade: "ترقية بريميوم",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور",
    resetPassword: "إعادة تعيين كلمة المرور",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    fullName: "الاسم الكامل",
    phone: "الهاتف",
    submit: "إرسال",
    logout: "تسجيل الخروج",
    atsHealth: "صحة ATS",
    applicationFunnel: "مسار الطلبات",
    skillRadar: "رادار المهارات",
    quickApply: "تقديم سريع + عرض ذكي",
    aiStudio: "استوديو الذكاء الاصطناعي",
    mockInterview: "وضع المقابلة التجريبية",
    welcomeBack: "مرحباً بعودتك",
    accessWorkspace: "ادخل إلى مساحة الباحث عن عمل.",
    createJobSeekerAccount: "إنشاء حساب باحث عن عمل",
    registrationWorkflow: "من التسجيل إلى التقديم في مسار واحد.",
    loginFailed: "فشل تسجيل الدخول",
    registrationFailed: "فشل التسجيل",
    authFailed: "فشل الطلب",
    resetLinkSent: "إذا كان البريد موجوداً فسيتم إرسال رابط إعادة التعيين.",
    passwordResetDone: "تمت إعادة تعيين كلمة المرور.",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    forgotPasswordQ: "هل نسيت كلمة المرور؟",
    sendResetLink: "إرسال رابط إعادة التعيين",
    haveTokenResetHere: "لديك الرمز بالفعل؟ أعد التعيين هنا",
    resetToken: "رمز إعادة التعيين",
    newPassword: "كلمة المرور الجديدة",
    resetPasswordBtn: "إعادة تعيين كلمة المرور",
    backToLogin: "العودة إلى تسجيل الدخول",
    authTagline: "ذكاء مهني مدعوم بالذكاء الاصطناعي",
    authHeadline: "مركز احترافي للباحث عن عمل",
    authDescription: "التسجيل، مختبر السيرة، المستشار الذكي، اكتشاف الشركات، ورؤى متقدمة.",
    goodMorning: "صباح الخير",
    seeker: "باحث",
    profileMatchPrefix: "ملفك يطابق",
    profileMatchMiddle: "مع",
    profileMatchSuffix: "وظائف جديدة.",
    currentCvStrength: "قوة السيرة الحالية",
    applied: "تم التقديم",
    interview: "مقابلة",
    offer: "عرض",
    marketLabel: "السوق",
    opportunitiesTitle: "خريطة الفرص",
    opportunitiesSubtitle: "بطاقات ذكية لا نهائية مع شدة التطابق والتقديم السريع.",
    uploadCvFirst: "ارفع سيرة ذاتية أولاً في مختبر السيرة",
    quickApplySuccess: "تم التقديم السريع مع العرض الذكي.",
    quickApplyFailed: "فشل التقديم السريع",
    match: "تطابق",
    company: "شركة",
    remote: "عن بُعد",
    save: "حفظ",
    loadMore: "تحميل المزيد",
    cvPreview: "معاينة السيرة",
    uploadCv: "رفع سيرة",
    deleteCv: "حذف السيرة",
    analyze: "تحليل",
    aiRecommendations: "توصيات الذكاء الاصطناعي",
    pasteBulletsPlaceholder: "ألصق نقاط السيرة للحصول على ملاحظات فورية...",
    weakPhrasing: "صياغة ضعيفة",
    noWeakPhrases: "لا توجد صياغات ضعيفة",
    strongImpact: "تأثير قوي",
    addImpactVerbs: "أضف أفعال تأثير أقوى",
    templateSwitcherNote: "مبدّل القوالب: استخدم تصدير المستشار الذكي إلى PDF/DOCX.",
    selectCvFirst: "اختر سيرة ذاتية أولاً",
    startSession: "بدء جلسة",
    selectSession: "اختر جلسة",
    askPlaceholder: "اسأل عن التحضير للمقابلة أو تحسين السيرة أو استراتيجية المسار...",
    send: "إرسال",
    marketTitle: "السوق",
    marketSubtitle: "استكشاف الشركات المعتمدة فقط مع لمحة عن بيئة العمل.",
    noDescriptionYet: "لا يوجد وصف بعد",
    cultureScore: "مؤشر الثقافة",
    consultantMarketplace: "سوق المستشارين",
    generalConsulting: "استشارة عامة",
    auditBookingTitle: "حجز تدقيق 15 دقيقة",
    selectConsultant: "اختر مستشاراً",
    auditGoalsPlaceholder: "اكتب أهدافك من هذه الجلسة...",
    bookSlot: "احجز 15 دقيقة",
    bookedSuccess: "تم حجز جلسة 15 دقيقة بنجاح.",
    bookingFailed: "فشل الحجز",
    consultantsLoadFailed: "فشل تحميل المستشارين.",
    selectConsultantAndTime: "اختر المستشار ووقت البداية",
    applicationsTitle: "الطلبات",
    applicationFallback: "طلب",
    savedJobs: "الوظائف المحفوظة",
    remove: "إزالة",
    notifications: "الإشعارات",
    markAsRead: "تحديد كمقروء",
    loading: "جارٍ التحميل",
    uploading: "جارٍ رفع السيرة...",
    cvUploadSuccess: "تم رفع السيرة بنجاح.",
    cvUploadFailed: "فشل رفع السيرة.",
    settingsSubtitle: "إدارة اللغة والمظهر وتفضيلات الحساب.",
    language: "اللغة",
    theme: "المظهر",
    themeDark: "داكن",
    themeLight: "فاتح",
    themePremium: "بريميوم",
    accountActions: "إجراءات الحساب",
    showAllNotifications: "عرض كل الإشعارات",
    noNotificationsYet: "لا توجد إشعارات حالياً.",
    unread: "غير مقروء",
    profileInfo: "معلومات الملف الشخصي",
    cvAiInsights: "رؤى الذكاء الاصطناعي للسيرة",
    noAiInsightsYet: "لا توجد رؤى بعد. قم بتحليل سيرتك في مختبر السيرة.",
    strengths: "نقاط القوة",
    weaknesses: "نقاط الضعف",
    recommendations: "التوصيات",
    noData: "لا توجد بيانات.",
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);
const KEY = "twt_seeker_language";

export const LanguageProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem(KEY);
    return stored === "ar" ? "ar" : "en";
  });

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    localStorage.setItem(KEY, language);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => dictionary[language][key] || key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
};
