import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import type { Language } from "../types/api";

type Dict = Record<string, string>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const en: Dict = {
    appTitle: "Talents We Trust | Job Seeker",
    pulse: "The Pulse",
    opportunities: "Opportunity Map",
    cvLab: "CV Lab",
    aiConsultant: "AI Consultant",
    aiConsultantIntro: "Build your CV with AI, then preview, refine, and export.",
    showSessions: "Show sessions",
    hideSessions: "Hide sessions",
    previewEmpty: "Keep chatting to build your CV.",
    exportDisabledHint: "Generate a preview to enable export.",
    insightsEmpty: "Insights will appear after the AI generates your CV.",
    startCareerAdvisor: "Career Advisor",
    startMockInterview: "Mock Interview",
    sessionMenu: "Session menu",
    renameSession: "Rename session",
    startNewSession: "Start new session",
    attachFile: "Attach file",
    sessions: "Sessions",
    noSessionsYet: "No sessions yet. Start a new one to build your CV.",
    sessionLabelCareer: "Career Advisor",
    sessionLabelMock: "Mock Interview",
    lastMessage: "Last message",
    chatPanel: "Conversation",
    insightsPanel: "Insights",
    previewPanel: "CV Preview",
    exportPanel: "Export",
    exportPdf: "Download PDF",
    exportDocx: "Download DOCX",
    exportFailed: "Export failed. Please try again.",
    previewLoading: "Loading preview...",
    previewFailed: "Preview unavailable.",
    refreshPreview: "Refresh preview",
    startFailed: "Failed to start session.",
    sendFailed: "Failed to send message.",
    sessionsLoadFailed: "Failed to load sessions.",
    chatEmpty: "Start a new session to build your CV with AI.",
    typing: "AI is typing",
    messageLabel: "Your message",
    selectSessionHint: "Select a session to continue.",
    market: "Market",
    consultants: "Consultants",
    applications: "Applications",
    profile: "Profile",
    settings: "Settings",
    searchPlaceholder: "Search jobs, companies, skills...",
    premiumUpgrade: "Premium Upgrade",
    login: "Login",
    register: "Create account",
    forgotPassword: "Forgot password",
    resetPassword: "Reset password",
    email: "Email",
    password: "Password",
    fullName: "Full name",
    phone: "Phone",
    submit: "Submit",
    logout: "Logout",
    atsHealth: "ATS Health",
    applicationFunnel: "Application Funnel",
    skillRadar: "Skill Radar",
    quickApply: "Quick Apply + Smart Pitch",
    aiStudio: "AI Studio",
    mockInterview: "Mock Interview Mode",
    welcomeBack: "Welcome Back",
    accessWorkspace: "Access your seeker workspace.",
    createJobSeekerAccount: "Create Job Seeker Account",
    registrationWorkflow: "From registration to applications in one workflow.",
    loginFailed: "Login failed",
    registrationFailed: "Registration failed",
    authFailed: "Failed",
    resetLinkSent: "If the email exists, a reset link has been sent.",
    passwordResetDone: "Password reset completed.",
    createAccount: "Create account",
    alreadyHaveAccount: "Already have an account?",
    forgotPasswordQ: "Forgot password?",
    sendResetLink: "Send reset link",
    haveTokenResetHere: "Have token already? Reset here",
    resetToken: "Reset Token",
    newPassword: "New Password",
    resetPasswordBtn: "Reset password",
    backToLogin: "Back to login",
    authTagline: "AI-Powered Career Intelligence",
    authHeadline: "Professional Job Seeker Command Center",
    authDescription: "Registration, CV Lab, AI consultant, market discovery, and premium insights.",
    goodMorning: "Good morning",
    seeker: "Seeker",
    profileMatchPrefix: "Your profile is a",
    profileMatchMiddle: "Match for",
    profileMatchSuffix: "new roles.",
    goToCvLab: "Go to CV Lab",
    browseJobs: "Browse jobs",
    startAiConsultant: "Start AI Consultant",
    currentCvStrength: "Current CV strength",
    applied: "Applied",
    interview: "Interview",
    offer: "Offer",
    marketLabel: "Market",
    opportunitiesTitle: "Opportunity Map",
    opportunitiesSubtitle: "Infinite smart cards with Match Intensity and Quick Apply.",
    apply: "Apply",
    viewDetails: "View details",
    matchUnavailable: "Match score coming soon",
    forYou: "For you",
    highlyMatched: "Highly matched",
    aiComingSoon: "AI coming soon",
    jobsLoadFailed: "Failed to load jobs.",
    noJobsFound: "No jobs found.",
    saved: "Saved",
    saveFailed: "Failed to save job.",
    jobDetailsFailed: "Failed to load job details.",
    jobDescription: "Description",
    jobRequirements: "Requirements",
    formLoadFailed: "Failed to load application form.",
    externalFormNote: "This job uses an external application form.",
    openExternalForm: "Open external form",
    selectOption: "Select an option",
    fileFieldNote: "Provide a link or reference (file upload not required).",
    coverLetter: "Cover letter",
    coverLetterPlaceholder: "Write a short cover letter...",
    chooseCv: "Choose a CV",
    selectCv: "Select a CV",
    cvRequired: "A CV is required for this application.",
    submitApplication: "Submit application",
    cancel: "Cancel",
    close: "Close",
    applicationSubmitted: "Application submitted successfully.",
    applyFailed: "Application failed. Please try again.",
    fieldRequired: "Field required",


    uploadCvFirst: "Upload CV first in CV Lab",
    quickApplySuccess: "Quick apply submitted with Smart Pitch.",
    quickApplyFailed: "Quick apply failed",
    match: "Match",
    company: "Company",
    remote: "Remote",
    save: "Save",
    loadMore: "Load More",
    cvPreview: "CV Preview",
    cvLabLeftHint: "Manage uploaded CV files, then run full AI analysis on the selected one.",
    cvTitle: "CV Title",
    cvTitlePlaceholder: "e.g. Senior Backend CV - 2026",
    uploadCv: "Upload CV",
    previewCv: "Preview CV",
    deleteCv: "Delete CV",
    confirmDeleteCv: "Are you sure you want to delete this CV?",
    noCvYet: "No CV uploaded yet.",
    analyze: "Analyze",
    aiAnalysis: "AI Analysis",
    aiSummary: "AI Summary",
    industryRanking: "Industry Rank",
    fullAiResponse: "Full AI Response",
    aiIntelligence: "AI Intelligence",
    featuresAnalytics: "Feature Analytics",
    structuredData: "Structured Data",
    rawAiResponse: "Raw AI Response",
    viewAnalysis: "View analysis",
    analysisHistory: "Analysis History",
    analysisHistoryEmpty: "No previous analysis runs yet.",
    analysisHistoryFailed: "Failed to load analysis history.",
    analysisLatest: "Latest",
    analysisRun: "Analysis run",
    templateSwitcherNote: "Template switcher: use AI Consultant export for PDF/DOCX generation.",
    selectCvFirst: "Select CV first",
    startSession: "Start Session",
    selectSession: "Select session",
    askPlaceholder: "Ask for interview prep, career strategy, CV improvements...",
    send: "Send",
    sending: "Sending",
                    marketTitle: "The Market",
    marketSubtitle: "Approved-only company discovery with culture signal preview.",
    marketSearchPlaceholder: "Search companies...",
    noCompaniesFound: "No companies found.",
    clearSearch: "Clear search",
    ratingPending: "Rating pending",
    viewCompany: "View details",
    viewAllJobs: "View all jobs",
    companyDetails: "Company details",
    companyOverview: "Overview",
    companyContact: "Contact",
    companyJobs: "Open roles",
    backToMarket: "Back to Market",
    companyEmail: "Email",
    companyPhone: "Phone",
    companyLoadFailed: "Failed to load company.",
    companyNotFound: "Company not found.",
    noJobsYet: "No jobs listed yet.",
    notProvided: "Not provided",
    filteredByCompany: "Filtered by company",
    noDescriptionYet: "No description yet",
    cultureScore: "Culture Score",
    consultantMarketplace: "Consultant Marketplace",
    consultingComingSoon: "Consulting coming soon",
    consultingComingSoonSubtitle: "Human consultant bookings are temporarily unavailable.",
    consultingComingSoonDetails: "We are onboarding verified consultants now. Check back soon to book a session.",
    generalConsulting: "General consulting",
    auditBookingTitle: "15-Min Audit Booking",
    selectConsultant: "Select consultant",
    auditGoalsPlaceholder: "Write your goals for this audit...",
    bookSlot: "Book 15-min Slot",
    bookedSuccess: "15-minute audit booked successfully.",
    bookingFailed: "Booking failed",
    consultantsLoadFailed: "Failed to load consultants.",
    selectConsultantAndTime: "Select consultant and start time",
    applicationsTitle: "Applications",
    applicationFallback: "Application",
    recentApplications: "Recent applications",
    viewAll: "View all",
    noApplicationsYet: "No applications yet.",
    savedJobs: "Saved Jobs",
    remove: "Remove",
    notifications: "Notifications",
    contact: "Contact",
    contactTitle: "Contact Us",
    contactSubtitle: "We read every message and respond quickly.",
    contactFormTitle: "Send a message",
    contactNote: "Report issues, share feature ideas, or request a mobile app or website. Our team reviews every message and responds quickly.",
    contactTalentsEmail: "Talents email",
    contactDevEmail: "Developer email",
    contactSubject: "Title",
    contactMessage: "Message",
    contactSubjectPlaceholder: "Short title for your request",
    contactMessagePlaceholder: "Describe the issue, suggestion, or request...",
    contactSubjectFallback: "Support request",
    contactMessageFallback: "Hi Talents team,",
    contactSend: "Send email",
    contactEmailsTitle: "Emails",
    contactSocialTitle: "Follow us",
    contactSocialNote: "Social links will be added soon.",

    markAsRead: "Mark as Read",
    loading: "Loading",
    retry: "Retry",
    dashboardLoadFailed: "Failed to load dashboard data.",
    uploading: "Uploading CV...",
    
    cvUploadSuccess: "CV uploaded successfully.",
    cvUploadFailed: "Failed to upload CV.",
    cvUploadLimitReached: "You can upload up to 3 CVs only.",
    cvAnalyzeFailed: "Could not analyze this CV right now. Please retry in a moment.",
    analyzingCv: "Analyzing CV...",
    analysisReady: "Analysis loaded successfully.",
    analysisPartial: "Partial analysis loaded. Some AI sections are unavailable.",
    cvAnalyzeOnceHint: "Each CV can be analyzed once. Upload a new CV to analyze again.",
    analyzeRequiredTitle: "Analyze your CV before applying",
    analyzeRequiredDesc: "To apply, upload your CV and run the AI analysis first. Then return here and apply again.",
    goToCvLab: "Go to CV Lab",
    enhanceTitle: "Enhance your CV with our AI Consultant",
    enhanceNow: "Enhance Now",
    enhanceStarting: "Sending...",
    enhanceDescription: "We will send your analysis to the AI Consultant and turn it into stronger, ATS-friendly CV language.",
    enhanceFailed: "Could not send to the AI Consultant. Please try again.",
    retryAnalysis: "Retry Analysis",
    settingsSubtitle: "Manage language, theme, and account preferences.",
    language: "Language",
    theme: "Theme",
    themeDark: "Dark",
    themeLight: "Light",
    themePremium: "Premium",
    accountActions: "Account Actions",
    showAllNotifications: "Show all notifications",
    noNotificationsYet: "No notifications yet.",
    unread: "Unread",
    profileInfo: "Profile Information",
    editProfile: "Edit Profile",
    cvAiInsights: "CV AI Insights",
    viewFullAnalysis: "View full analysis",
    noAiInsightsYet: "No AI insights yet. Analyze your CV in CV Lab.",
    atsScoreHint: "70+ is strong. Improve keywords and structure to raise this score.",
    strengths: "Strengths",
    weaknesses: "Weaknesses",
    recommendations: "Recommendations",
    savedJobsLoadFailed: "Could not load saved jobs.",
    viewJob: "View job",
    confirmRemoveSaved: "Remove this job from saved?",
    atsScore: "ATS Score",
    experienceYears: "Experience",
    keySkills: "Key Skills",
    yearsSuffix: "y",
        noData: "No data available.",
    sessionTitle: "Session title",
    titlePlaceholder: "e.g. CV draft for Google",
    saveTitle: "Save title",
    titleSaved: "Title saved",
    deleteSession: "Delete session",
    sessionDeleted: "Session deleted",
    confirmDeleteSession: "Delete this session? This cannot be undone.",
    renameFailed: "Failed to rename session.",
    deleteFailed: "Failed to delete session.",
    insightsLoading: "Loading insights...",
    insightsFailed: "Failed to load insights.",
    insightsScore: "CV Score",
    insightsChecklist: "Checklist",
    insightsSummary: "Summary",
    insightsImprovements: "Improvements",
    insightsRequirements: "Job requirements",
    rewriteTitle: "Original vs Improved",
    summaryLabel: "Summary",
    experienceLabel: "Experience",
    projectLabel: "Project",
    originalText: "Original",
    improvedText: "Improved",
    insightsStatusComplete: "CV is complete",
    insightsStatusInProgress: "CV is in progress",
    scoreHintExcellent: "Excellent. You're in a strong position.",
    scoreHintGood: "Good. A few improvements could help.",
    scoreHintImprove: "Needs work. Focus on keywords and impact.",
    untitledSession: "Untitled session",
    recommendedJobs: "Recommended jobs",
};

const ar: Dict = {
  appTitle: "Talents We Trust | الباحث عن عمل",
  pulse: "نبض السوق",
  opportunities: "خريطة الفرص",
  cvLab: "مختبر السيرة",
  aiConsultant: "المستشار الذكي",
  aiConsultantIntro: "أنشئ سيرتك بالذكاء الاصطناعي ثم عاينها وطوّرها وصدّرها.",
  showSessions: "إظهار الجلسات",
  hideSessions: "إخفاء الجلسات",
  previewEmpty: "واصل المحادثة لبناء سيرتك.",
  exportDisabledHint: "أنشئ معاينة لتفعيل التصدير.",
  insightsEmpty: "ستظهر الرؤى بعد أن ينشئ الذكاء الاصطناعي سيرتك.",
  startCareerAdvisor: "مستشار المسار",
  startMockInterview: "مقابلة تجريبية",
  sessionMenu: "قائمة الجلسة",
  renameSession: "إعادة تسمية الجلسة",
  startNewSession: "بدء جلسة جديدة",
  attachFile: "إرفاق ملف",
  sessions: "الجلسات",
  noSessionsYet: "لا توجد جلسات بعد. ابدأ جلسة جديدة لبناء سيرتك.",
  sessionLabelCareer: "مستشار المسار",
  sessionLabelMock: "مقابلة تجريبية",
  lastMessage: "آخر رسالة",
  chatPanel: "المحادثة",
  insightsPanel: "الرؤى",
  previewPanel: "معاينة السيرة",
  exportPanel: "تصدير",
  exportPdf: "تنزيل PDF",
  exportDocx: "تنزيل DOCX",
  exportFailed: "فشل التصدير. حاول مرة أخرى.",
  previewLoading: "جارٍ تحميل المعاينة...",
  previewFailed: "المعاينة غير متاحة.",
  refreshPreview: "تحديث المعاينة",
  startFailed: "فشل بدء الجلسة.",
  sendFailed: "فشل إرسال الرسالة.",
  sessionsLoadFailed: "فشل تحميل الجلسات.",
  chatEmpty: "ابدأ جلسة جديدة لبناء سيرتك بالذكاء الاصطناعي.",
  typing: "الذكاء الاصطناعي يكتب",
  messageLabel: "رسالتك",
  selectSessionHint: "اختر جلسة للمتابعة.",
  market: "السوق",
  consultants: "المستشارون",
  applications: "الطلبات",
  profile: "الملف الشخصي",
  settings: "الإعدادات",
  searchPlaceholder: "ابحث عن وظائف، شركات، مهارات...",
  premiumUpgrade: "ترقية بريميوم",
  login: "تسجيل الدخول",
  register: "إنشاء حساب",
  forgotPassword: "نسيت كلمة المرور",
  resetPassword: "إعادة تعيين كلمة المرور",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  fullName: "الاسم الكامل",
  phone: "الهاتف",
  submit: "إرسال",
  logout: "تسجيل الخروج",
  atsHealth: "صحة ATS",
  applicationFunnel: "قمع التقديم",
  skillRadar: "رادار المهارات",
  quickApply: "تقديم سريع + عرض ذكي",
  aiStudio: "استوديو الذكاء الاصطناعي",
  mockInterview: "وضع مقابلة تجريبية",
  welcomeBack: "مرحبًا بعودتك",
  accessWorkspace: "ادخل إلى مساحة الباحث عن عمل.",
  createJobSeekerAccount: "إنشاء حساب باحث عن عمل",
  registrationWorkflow: "من التسجيل إلى التقديم في مسار واحد.",
  loginFailed: "فشل تسجيل الدخول",
  registrationFailed: "فشل التسجيل",
  authFailed: "فشل",
  resetLinkSent: "إن وجد البريد، فسيتم إرسال رابط إعادة التعيين.",
  passwordResetDone: "تمت إعادة تعيين كلمة المرور.",
  createAccount: "إنشاء حساب",
  alreadyHaveAccount: "لديك حساب؟",
  forgotPasswordQ: "نسيت كلمة المرور؟",
  sendResetLink: "إرسال رابط إعادة التعيين",
  haveTokenResetHere: "لديك رمز؟ أعد التعيين هنا",
  resetToken: "رمز إعادة التعيين",
  newPassword: "كلمة مرور جديدة",
  resetPasswordBtn: "إعادة تعيين كلمة المرور",
  backToLogin: "العودة لتسجيل الدخول",
  authTagline: "ذكاء مهني مدعوم بالذكاء الاصطناعي",
  authHeadline: "مركز تحكم الباحث عن عمل",
  authDescription: "التسجيل، مختبر السيرة، المستشار الذكي، اكتشاف السوق، ورؤى مميزة.",
  goodMorning: "صباح الخير",
  seeker: "باحث",
  profileMatchPrefix: "ملفك الشخصي",
  profileMatchMiddle: "متوافق مع",
  profileMatchSuffix: "وظائف جديدة.",
  goToCvLab: "الانتقال إلى مختبر السيرة",
  browseJobs: "تصفح الوظائف",
  startAiConsultant: "ابدأ المستشار الذكي",
  currentCvStrength: "قوة السيرة الحالية",
  applied: "تم التقديم",
  interview: "مقابلة",
  offer: "عرض",
  marketLabel: "السوق",
  opportunitiesTitle: "خريطة الفرص",
  opportunitiesSubtitle: "بطاقات ذكية مع شدة المطابقة وتقديم سريع.",
  apply: "قدّم",
  viewDetails: "عرض التفاصيل",
  matchUnavailable: "درجة المطابقة قريبًا",
  forYou: "مناسب لك",
  highlyMatched: "مطابقة عالية",
  aiComingSoon: "الذكاء الاصطناعي قريبًا",
  jobsLoadFailed: "فشل تحميل الوظائف.",
  noJobsFound: "لا توجد وظائف.",
  saved: "محفوظ",
  saveFailed: "فشل حفظ الوظيفة.",
  jobDetailsFailed: "فشل تحميل تفاصيل الوظيفة.",
  jobDescription: "الوصف",
  jobRequirements: "المتطلبات",
  formLoadFailed: "فشل تحميل نموذج التقديم.",
  externalFormNote: "هذه الوظيفة تستخدم نموذجًا خارجيًا.",
  openExternalForm: "فتح النموذج الخارجي",
  selectOption: "اختر خيارًا",
  fileFieldNote: "قدّم رابطًا أو مرجعًا (لا يلزم رفع ملف).",
  coverLetter: "خطاب تغطية",
  coverLetterPlaceholder: "اكتب خطاب تغطية قصيرًا...",
  chooseCv: "اختر سيرة",
  selectCv: "اختر السيرة",
  cvRequired: "السيرة مطلوبة لهذا التقديم.",
  submitApplication: "إرسال الطلب",
  cancel: "إلغاء",
  close: "إغلاق",
  applicationSubmitted: "تم إرسال الطلب بنجاح.",
  applyFailed: "فشل التقديم. حاول مرة أخرى.",
  fieldRequired: "هذا الحقل مطلوب",
  uploadCvFirst: "ارفع سيرة أولًا في مختبر السيرة",
  quickApplySuccess: "تم التقديم السريع مع العرض الذكي.",
  quickApplyFailed: "فشل التقديم السريع",
  match: "مطابقة",
  company: "الشركة",
  remote: "عن بُعد",
  save: "حفظ",
  loadMore: "تحميل المزيد",
  cvPreview: "معاينة السيرة",
  cvLabLeftHint: "أدِر ملفات السير الذاتية المرفوعة ثم شغّل التحليل الكامل على الملف المحدد.",
  cvTitle: "عنوان السيرة",
  cvTitlePlaceholder: "مثال: سيرة مطور Backend - 2026",
  uploadCv: "رفع سيرة",
  previewCv: "معاينة السيرة",
  deleteCv: "حذف السيرة",
  confirmDeleteCv: "هل تريد حذف هذه السيرة؟",
  noCvYet: "لا توجد سيرة مرفوعة بعد.",
  analyze: "تحليل",
  aiAnalysis: "تحليل الذكاء الاصطناعي",
  aiSummary: "ملخص الذكاء الاصطناعي",
  industryRanking: "الترتيب الصناعي",
  fullAiResponse: "الاستجابة الكاملة للذكاء الاصطناعي",
  aiIntelligence: "ذكاء اصطناعي",
  featuresAnalytics: "تحليلات الميزات",
  structuredData: "بيانات مهيكلة",
  rawAiResponse: "استجابة الذكاء الاصطناعي الخام",
  viewAnalysis: "عرض التحليل",
  analysisHistory: "سجل التحليل",
  analysisHistoryEmpty: "لا توجد تحليلات سابقة بعد.",
  analysisHistoryFailed: "تعذر تحميل سجل التحليل.",
  analysisLatest: "الأحدث",
  analysisRun: "جلسة تحليل",
  templateSwitcherNote: "مبدّل القوالب: استخدم تصدير المستشار الذكي لإنشاء PDF/DOCX.",
  selectCvFirst: "اختر سيرة أولًا",
  startSession: "بدء جلسة",
  selectSession: "اختر جلسة",
  askPlaceholder: "اسأل عن التحضير للمقابلات، الاستراتيجية المهنية، تحسين السيرة...",
  send: "إرسال",
  sending: "جارٍ الإرسال",
  marketTitle: "السوق",
  marketSubtitle: "اكتشاف الشركات المعتمدة فقط مع لمحة عن الثقافة.",
  marketSearchPlaceholder: "ابحث عن الشركات...",
  noCompaniesFound: "لا توجد شركات.",
  clearSearch: "مسح البحث",
  ratingPending: "التقييم قيد الانتظار",
  viewCompany: "عرض التفاصيل",
  viewAllJobs: "عرض كل الوظائف",
  companyDetails: "تفاصيل الشركة",
  companyOverview: "نظرة عامة",
  companyContact: "التواصل",
  companyJobs: "وظائف متاحة",
  backToMarket: "العودة إلى السوق",
  companyEmail: "البريد الإلكتروني",
  companyPhone: "الهاتف",
  companyLoadFailed: "تعذر تحميل الشركة.",
  companyNotFound: "لم يتم العثور على شركة.",
  noJobsYet: "لا توجد وظائف بعد.",
  notProvided: "غير متوفر",
  filteredByCompany: "مُفلتر حسب الشركة",
  noDescriptionYet: "لا يوجد وصف بعد",
  cultureScore: "مؤشر الثقافة",
  consultantMarketplace: "سوق المستشارين",
  consultingComingSoon: "الاستشارات قريبًا",
  consultingComingSoonSubtitle: "الحجوزات مع المستشارين غير متاحة مؤقتًا.",
  consultingComingSoonDetails: "نقوم بضم مستشارين موثوقين الآن. عد قريبًا لحجز جلسة.",
  generalConsulting: "استشارات عامة",
  auditBookingTitle: "حجز مراجعة لمدة 15 دقيقة",
  selectConsultant: "اختر مستشارًا",
  auditGoalsPlaceholder: "اكتب أهدافك لهذه المراجعة...",
  bookSlot: "حجز مدة 15 دقيقة",
  bookedSuccess: "تم الحجز لمدة 15 دقيقة بنجاح.",
  bookingFailed: "فشل الحجز",
  consultantsLoadFailed: "فشل تحميل المستشارين.",
  selectConsultantAndTime: "اختر المستشار والوقت",
  applicationsTitle: "الطلبات",
  applicationFallback: "طلب",
  recentApplications: "أحدث الطلبات",
  viewAll: "عرض الكل",
  noApplicationsYet: "لا توجد طلبات بعد.",
  savedJobs: "الوظائف المحفوظة",
  remove: "إزالة",
  notifications: "الإشعارات",
  contact: "تواصل",
  contactTitle: "تواصل معنا",
  contactSubtitle: "نقرأ كل رسالة ونرد بسرعة.",
  contactFormTitle: "أرسل رسالة",
  contactNote: "أبلغ عن مشكلة أو اقترح ميزة أو اطلب تطبيقًا. سنرد بسرعة.",
  contactTalentsEmail: "بريد Talents",
  contactDevEmail: "بريد المطور",
  contactSubject: "العنوان",
  contactMessage: "الرسالة",
  contactSubjectPlaceholder: "عنوان قصير لطلبك",
  contactMessagePlaceholder: "اشرح المشكلة أو الاقتراح...",
  contactSubjectFallback: "طلب دعم",
  contactMessageFallback: "مرحبًا فريق Talents،",
  contactSend: "إرسال البريد",
  contactEmailsTitle: "البريد",
  contactSocialTitle: "تابعنا",
  contactSocialNote: "سيتم إضافة الروابط قريبًا.",
  markAsRead: "تحديد كمقروء",
  loading: "جارٍ التحميل",
  retry: "إعادة المحاولة",
  dashboardLoadFailed: "تعذر تحميل بيانات اللوحة.",
  uploading: "جارٍ رفع السيرة...",
  cvUploadSuccess: "تم رفع السيرة بنجاح.",
  cvUploadFailed: "فشل رفع السيرة.",
  cvUploadLimitReached: "يمكنك رفع 3 سير ذاتية كحد أقصى.",
  cvAnalyzeFailed: "تعذر تحليل السيرة الآن. حاول لاحقًا.",
  analyzingCv: "جارٍ تحليل السيرة...",
  analysisReady: "تم تحميل التحليل بنجاح.",
  analysisPartial: "تم تحميل التحليل جزئيًا. بعض الأقسام غير متاحة.",
  cvAnalyzeOnceHint: "يمكن تحليل كل سيرة ذاتية مرة واحدة فقط. ارفع سيرة جديدة للتحليل.",
  analyzeRequiredTitle: "حلل سيرتك قبل التقديم",
  analyzeRequiredDesc: "للتقديم يجب رفع السيرة وتحليلها بالذكاء أولاً، ثم العودة للتقديم.",
  goToCvLab: "الانتقال إلى مختبر السيرة",
  enhanceTitle: "حسّن سيرتك مع المستشار الذكي",
  enhanceNow: "ابدأ التحسين",
  enhanceStarting: "جارٍ الإرسال...",
  enhanceDescription: "سنرسل التحليل إلى المستشار الذكي لتحويله إلى صياغة احترافية مناسبة للـ ATS.",
  enhanceFailed: "تعذر الإرسال إلى المستشار الذكي. حاول مرة أخرى.",
  retryAnalysis: "أعد التحليل",
  settingsSubtitle: "إدارة اللغة والمظهر وتفضيلات الحساب.",
  language: "اللغة",
  theme: "السمة",
  themeDark: "داكن",
  themeLight: "فاتح",
  themePremium: "مميز",
  accountActions: "إجراءات الحساب",
  showAllNotifications: "عرض كل الإشعارات",
  noNotificationsYet: "لا توجد إشعارات بعد.",
  unread: "غير مقروء",
  profileInfo: "معلومات الملف الشخصي",
  editProfile: "تعديل الملف",
  cvAiInsights: "رؤى السيرة بالذكاء الاصطناعي",
  viewFullAnalysis: "عرض التحليل الكامل",
  noAiInsightsYet: "لا توجد رؤى بعد. حلّل سيرتك في مختبر السيرة.",
  atsScoreHint: "درجة 70+ ممتازة. حسّن الكلمات المفتاحية والبنية لرفع النتيجة.",
  strengths: "نقاط القوة",
  weaknesses: "نقاط الضعف",
  recommendations: "التوصيات",
  savedJobsLoadFailed: "تعذر تحميل الوظائف المحفوظة.",
  viewJob: "عرض الوظيفة",
  confirmRemoveSaved: "إزالة هذه الوظيفة من المحفوظات؟",
  atsScore: "درجة ATS",
  experienceYears: "الخبرة",
  keySkills: "المهارات الأساسية",
  yearsSuffix: "س",
  noData: "لا توجد بيانات.",
  sessionTitle: "عنوان الجلسة",
  titlePlaceholder: "مثال: مسودة سيرة لجوجل",
  saveTitle: "حفظ العنوان",
  titleSaved: "تم حفظ العنوان",
  deleteSession: "حذف الجلسة",
  sessionDeleted: "تم حذف الجلسة",
  confirmDeleteSession: "هل تريد حذف هذه الجلسة؟ لا يمكن التراجع.",
  renameFailed: "تعذر تغيير العنوان.",
  deleteFailed: "تعذر حذف الجلسة.",
  insightsLoading: "جارٍ تحميل الرؤى...",
  insightsFailed: "تعذر تحميل الرؤى.",
  insightsScore: "درجة السيرة",
  insightsChecklist: "قائمة التحقق",
  insightsSummary: "الملخص",
  insightsImprovements: "تحسينات",
  insightsRequirements: "متطلبات الوظيفة",
  rewriteTitle: "النص الأصلي والمُحسّن",
  summaryLabel: "الملخص",
  experienceLabel: "الخبرة",
  projectLabel: "المشروع",
  originalText: "الأصل",
  improvedText: "المُحسّن",
  insightsStatusComplete: "السيرة مكتملة",
  insightsStatusInProgress: "السيرة قيد الإعداد",
  scoreHintExcellent: "ممتاز. أنت في وضع قوي.",
  scoreHintGood: "جيد. بعض التحسينات ستساعد.",
  scoreHintImprove: "يحتاج إلى تحسين. ركّز على الكلمات المفتاحية والأثر.",
  untitledSession: "جلسة بدون عنوان",
  recommendedJobs: "وظائف مقترحة",
};

const dictionary: Record<Language, Dict> = {
  en,
  ar,
};

const LanguageContext = createContext<LanguageContextValue | null>(null);
const KEY = "twt_seeker_language";

export const LanguageProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem(KEY);
    return stored === "ar" ? "ar" : "en";
  });

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    localStorage.setItem(KEY, language);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => dictionary[language][key] || key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
};























